# Generated by Django 5.2.4 on 2025-08-03 00:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_administrator_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number')),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='user_administrator',
            new_name='UserAdministrator',
        ),
        migrations.RenameModel(
            old_name='user_employee',
            new_name='UserEmployee',
        ),
        migrations.RenameModel(
            old_name='user_supplier',
            new_name='UserSupplier',
        ),
        migrations.DeleteModel(
            name='user_customer',
        ),
    ]
